### ISSUE TITLE
About Alpha Camp 的 Array 資料彙整進入一個 Dictionary，current index 存入 index 的 array

### ISSUE THREAD

**Issue by edwardinubuntu** [PiHanHsu/ALPHACampApp#12]
Dictionary
- Key: 老師 Value: 老師資料 Array
- Key: 核心人員 Value: 核心人員的 Array
- Key: 校友 Value: 校友 Array

藉由不同的 Switch 來取值。

再宣告 int[] pageUsedIndexes
[0] = 老師頁的 Index
[1] = 核心人員的 Index
[2] = 校友的 Index

當切換 Switch 先把 current index update 回去 pageUsedIndexes，再重新配額 currentIndex 與 currentArray。

最後再 Refresh 畫面。

**Comment by PiHanHsu** [comment]
Done
