### ISSUE TITLE
Cannot sign up without a password

### ISSUE THREAD

**Issue by edwardinubuntu** [PiHanHsu/ALPHACampApp#2]
在輸入完如附圖時候出現錯誤訊息。

2015-02-02 17:21:03.286 ALPHACampApp[6758:3460478] **\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Cannot sign up without a password.'
**\* First throw call stack:
(
    0   CoreFoundation                      0x000000010b13ef35 **exceptionPreprocess + 165
    1   libobjc.A.dylib                     0x000000010add7bb7 objc_exception_throw + 45
    2   CoreFoundation                      0x000000010b13ee6d +[NSException raise:format:] + 205
    3   ALPHACampApp                        0x000000010945bcff -[PFUser(Private) checkSignUpParams] + 177
    4   ALPHACampApp                        0x0000000109463b64 -[PFUser signUpInBackgroundWithBlock:] + 219
    5   ALPHACampApp                        0x000000010939af32 -[RegisterViewController registerButtonPressed:] + 1778
    6   UIKit                               0x000000010b52c8be -[UIApplication sendAction:to:from:forEvent:] + 75
    7   UIKit                               0x000000010b633410 -[UIControl _sendActionsForEvents:withEvent:] + 467
    8   UIKit                               0x000000010b6327df -[UIControl touchesEnded:withEvent:] + 522
    9   UIKit                               0x000000010b572308 -[UIWindow _sendTouchesForEvent:] + 735
    10  UIKit                               0x000000010b572c33 -[UIWindow sendEvent:] + 683
    11  UIKit                               0x000000010b53f9b1 -[UIApplication sendEvent:] + 246
    12  UIKit                               0x000000010b54ca7d _UIApplicationHandleEventFromQueueEvent + 17370
    13  UIKit                               0x000000010b528103 _UIApplicationHandleEventQueue + 1961
    14  CoreFoundation                      0x000000010b074551 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION** + 17
    15  CoreFoundation                      0x000000010b06a41d __CFRunLoopDoSources0 + 269
    16  CoreFoundation                      0x000000010b069a54 __CFRunLoopRun + 868
    17  CoreFoundation                      0x000000010b069486 CFRunLoopRunSpecific + 470
    18  GraphicsServices                    0x000000010d59a9f0 GSEventRunModal + 161
    19  UIKit                               0x000000010b52b420 UIApplicationMain + 1282
    20  ALPHACampApp                        0x000000010939a753 main + 115
    21  libdyld.dylib                       0x000000010c934145 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 

![ios simulator screen shot 2015 2 2 5 21 17](https://cloud.githubusercontent.com/assets/414554/5998304/be35cf6e-ab00-11e4-8209-147fed1087b7.png)

**Comment by edwardinubuntu** [comment]
推敲碰到原因是密碼輸入兩次不一致。這個要幫使用者擋。

**Comment by PiHanHsu** [comment]
奇怪 這個我有寫if判斷式ㄝ
等等check一下

**Comment by edwardinubuntu** [comment]
記得加上 Return 就解了。
